repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        language: system
        entry: pylint
        args:
          - conduit
          - --disable=C, R, W0221, E1101, E0401
          - --enable=R1705
